=== chain-registry/chain-registry/registries/minimal/chain.schema.json
{
  "$id": "https://sikka.tech/chain.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Chain",
  "description": "Chain.json is a metadata file that contains information about a blockchain.",
  "type": "object",
  "required": [
    "$schema",
    "chainName",
    "chainType"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "pattern": "^(\\.\\./)+chain\\.schema\\.json$"
    },
    "website": {
      "type": "string",
      "minLength": 1,
      "format": "uri"
    },
    "slip44": {
      "type": "number"
    },
    "fees": {
      "type": "object",
      "required": [
        "feeTokens"
      ],
      "properties": {
        "feeTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/feeToken"
          }
        }
      },
      "additionalProperties": false
    },
    "staking": {
      "type": "object",
      "required": [
        "stakingTokens"
      ],
      "properties": {
        "stakingTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/stakingToken"
          }
        },
        "lockDuration": {
          "type": "object",
          "properties": {
            "blocks": {
              "type": "number",
              "description": "The number of blocks for which the staked tokens are locked."
            },
            "time": {
              "type": "string",
              "minLength": 1,
              "description": "The approximate time for which the staked tokens are locked."
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "codebase": {
      "type": "object",
      "properties": {
        "tag": {
          "$ref": "#/$defs/tag"
        },
        "language": {
          "$ref": "#/$defs/language"
        },
        "sdk": {
          "$ref": "#/$defs/sdk"
        },
        "cosmwasm": {
          "$ref": "#/$defs/cosmwasm"
        },
        "ibc": {
          "$ref": "#/$defs/ibc"
        }
      },
      "additionalProperties": false
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "png": {
            "type": "string",
            "minLength": 1,
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
          },
          "svg": {
            "type": "string",
            "minLength": 1,
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
          },
          "theme": {
            "type": "object",
            "properties": {
              "circle": {
                "type": "boolean"
              },
              "darkMode": {
                "type": "boolean"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          },
          "imageSync": {
            "$ref": "#/$defs/pointer"
          }
        },
        "anyOf": [
          {
            "required": [
              "png"
            ]
          },
          {
            "required": [
              "svg"
            ]
          }
        ],
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "maxLength": 3000
    },
    "apis": {
      "type": "object",
      "properties": {
        "rpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "rest": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "wss": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpcWeb": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "evmHttpJsonrpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        }
      },
      "additionalProperties": false
    },
    "snapshots": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/snapshot"
      }
    },
    "explorers": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/explorer"
      }
    },
    "keywords": {
      "type": "array",
      "maxContains": 20,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "chainName": {
      "type": "string",
      "minLength": 1,
      "pattern": "[a-z0-9]+"
    },
    "chainType": {
      "type": "string",
      "minLength": 1,
      "enum": [
        "cosmos",
        "eip155",
        "bip122",
        "polkadot",
        "solana",
        "algorand",
        "arweave",
        "ergo",
        "fil",
        "hedera",
        "monero",
        "reef",
        "stacks",
        "starknet",
        "stellar",
        "tezos",
        "vechain",
        "waves",
        "xrpl",
        "unknown"
      ],
      "description": "The 'type' of chain as the corresponding CAIP-2 Namespace value. E.G., 'cosmos' or 'eip155'. Namespaces cna be found here: https://github.com/ChainAgnostic/namespaces/tree/main."
    },
    "chainId": {
      "type": "string",
      "minLength": 1
    },
    "preForkChainName": {
      "type": "string",
      "minLength": 1,
      "pattern": "[a-z0-9]+"
    },
    "prettyName": {
      "type": "string",
      "minLength": 1
    },
    "networkType": {
      "enum": [
        "mainnet",
        "testnet",
        "devnet"
      ]
    },
    "bech32Prefix": {
      "type": "string",
      "minLength": 1,
      "description": "The default prefix for the human-readable part of addresses that identifies the coin type. Must be registered with SLIP-0173. E.g., 'cosmos'"
    },
    "nodeHome": {
      "type": "string",
      "minLength": 1
    },
    "keyAlgos": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "secp256k1",
          "ethsecp256k1",
          "ed25519",
          "sr25519",
          "bn254"
        ],
        "uniqueItems": true
      }
    },
    "extraCodecs": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "enum": [
          "ethermint",
          "injective"
        ],
        "uniqueItems": true
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "endpoint": {
      "type": "object",
      "required": [
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "snapshot": {
      "type": "object",
      "required": [
        "provider",
        "url"
      ],
      "properties": {
        "provider": {
          "type": "string",
          "minLength": 1
        },
        "url": {
          "type": "string",
          "minLength": 1
        },
        "type": {
          "type": "string",
          "enum": [
            "pruned",
            "archive"
          ]
        },
        "frequency": {
          "type": "string",
          "minLength": 1
        },
        "compression": {
          "type": "string",
          "enum": [
            "lz4",
            "zstd",
            "gzip",
            "tar",
            "none"
          ]
        },
        "latestUrl": {
          "type": "string",
          "minLength": 1
        },
        "dbBackend": {
          "type": "string",
          "enum": [
            "goleveldb",
            "pebbledb"
          ]
        },
        "checksumAvailable": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "explorer": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "minLength": 1
        },
        "url": {
          "type": "string",
          "minLength": 1
        },
        "txPage": {
          "type": "string",
          "minLength": 1
        },
        "accountPage": {
          "type": "string",
          "minLength": 1
        },
        "validatorPage": {
          "type": "string",
          "minLength": 1
        },
        "proposalPage": {
          "type": "string",
          "minLength": 1
        },
        "blockPage": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "repo": {
      "type": "string",
      "format": "uri",
      "minLength": 1,
      "description": "URL of the code repository."
    },
    "version": {
      "type": "string",
      "minLength": 1,
      "pattern": "^v?\\d+(\\.\\d+){0,2}$",
      "description": "Simple version string (e.g., 'v1.0.0')."
    },
    "tag": {
      "type": "string",
      "minLength": 1,
      "pattern": "^[A-Za-z0-9._/@-]+$",
      "description": "Git Upgrade Tag"
    },
    "sdk": {
      "type": "object",
      "required": [
        "type"
      ],
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "cosmos",
            "penumbra",
            "other"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        }
      }
    },
    "ibc": {
      "type": "object",
      "required": [
        "type"
      ],
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "go",
            "rust",
            "other"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        },
        "icsEnabled": {
          "type": "array",
          "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
          "items": {
            "type": "string",
            "minLength": 1,
            "description": "IBC app or ICS standard.",
            "enum": [
              "ics20-1",
              "ics27-1",
              "mauth"
            ]
          }
        }
      }
    },
    "cosmwasm": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        },
        "enabled": {
          "type": "boolean"
        },
        "path": {
          "type": "string",
          "minLength": 1,
          "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
          "pattern": "^\\$HOME.*$"
        }
      }
    },
    "consensus": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "tendermint",
            "cometbft",
            "sei-tendermint",
            "cometbls"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        }
      },
      "additionalProperties": false
    },
    "language": {
      "type": "object",
      "required": [
        "type"
      ],
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "go",
            "rust",
            "solidity",
            "other"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        }
      }
    },
    "binaries": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "linux/amd64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "linux/arm64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "darwin/amd64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "darwin/arm64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "windows/amd64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "windows/arm64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        }
      }
    },
    "pointer": {
      "type": "object",
      "description": "The (primary) key used to identify an object within the Chain Registry.",
      "required": [
        "chainName"
      ],
      "properties": {
        "chainName": {
          "type": "string",
          "minLength": 1,
          "description": "The chain name or platform from which the object resides. E.g., 'cosmoshub', 'ethereum', 'forex', or 'nasdaq'"
        },
        "baseDenom": {
          "type": "string",
          "minLength": 1,
          "description": "The base denom of the asset from which the object originates. E.g., when describing ATOM from Cosmos Hub, specify 'uatom', NOT 'atom' nor 'ATOM'; base units are unique per platform."
        }
      },
      "additionalProperties": false
    },
    "feeToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string",
          "minLength": 1
        },
        "fixedMinGasPrice": {
          "type": "number"
        },
        "lowGasPrice": {
          "type": "number"
        },
        "averageGasPrice": {
          "type": "number"
        },
        "highGasPrice": {
          "type": "number"
        },
        "gasCosts": {
          "type": "object",
          "properties": {
            "cosmosSend": {
              "type": "number"
            },
            "ibcTransfer": {
              "type": "number"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "stakingToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "chain_type": {
            "const": "cosmos"
          }
        }
      },
      "then": {
        "required": [
          "bech32_prefix"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "chain_type": {
            "enum": [
              "cosmos",
              "eip155"
            ]
          }
        }
      },
      "then": {
        "required": [
          "chain_id"
        ]
      }
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/testnets/iopntestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chainName": "iopntestnet",
  "website": "https://iopn.tech/",
  "networkType": "testnet",
  "chainType": "cosmos",
  "prettyName": "Iopn",
  "chainId": "iopn_984-1",
  "bech32Prefix": "gwei",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "gwei",
        "fixedMinGasPrice": 0,
        "lowGasPrice": 0,
        "averageGasPrice": 0.025,
        "highGasPrice": 0.04
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "gwei"
      }
    ],
    "lockDuration": {
      "time": "1209600s"
    }
  },
  "codebase": {
    "sdk": {
      "type": "cosmos",
      "version": "0.47.5"
    }
  },
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/iopntestnet/images/iopn_Dark.png"
    }
  ],
  "apis": {
    "rpc": [
      {
        "address": "https://testnet-rpc.iopn.tech/"
      }
    ],
    "rest": [
      {
        "address": "https://testnet-rpc2.iopn.tech/"
      }
    ]
  },
  "explorers": [
    {
      "kind": "explorer",
      "url": "https://testnet.iopn.tech/"
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/testnets/xiontestnet2/chain.json
{
  "$schema": "../../chain.schema.json",
  "chainName": "xiontestnet2",
  "chainType": "cosmos",
  "chainId": "xion-testnet-2",
  "prettyName": "Xion Testnet 2",
  "website": "https://xion.burnt.com",
  "networkType": "testnet",
  "bech32Prefix": "xion",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "uxion",
        "fixedMinGasPrice": 0.001,
        "lowGasPrice": 0.001,
        "averageGasPrice": 0.001,
        "highGasPrice": 0.01
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uxion"
      }
    ]
  },
  "codebase": {
    "sdk": {
      "type": "cosmos",
      "version": "v0.50.11"
    },
    "cosmwasm": {
      "version": "v0.53.0",
      "enabled": true
    }
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.xion-testnet-2.burnt.com:443"
      }
    ],
    "rest": [
      {
        "address": "https://api.xion-testnet-2.burnt.com"
      }
    ],
    "grpc": [
      {
        "address": "grpc.xion-testnet-2.burnt.com:443"
      }
    ]
  },
  "explorers": [
    {
      "url": "https://explorer.burnt.com/xion-testnet-2",
      "txPage": "https://explorer.burnt.com/xion-testnet-2/tx/${txHash}",
      "accountPage": "https://explorer.burnt.com/xion-testnet-2/account/${accountAddress}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/xion/images/burnt.png"
    }
  ],
  "description": "XION is the first walletless L1 blockchain purpose built for consumer adoption through chain abstraction."
}

=== chain-registry/chain-registry/registries/minimal/testnets/deardogetestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chainName": "deardogetestnet",
  "chainType": "cosmos",
  "chainId": "deardoge-testnet",
  "prettyName": "Dear Doge Testnet",
  "networkType": "testnet",
  "bech32Prefix": "deardoge",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "udear",
        "fixedMinGasPrice": 0.25
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "udear"
      }
    ]
  },
  "codebase": {

  },
  "apis": {
    "rpc": [
      {
        "address": "https://testnet-rpc.deardoge.org"
      }
    ],
    "rest": [
      {
        "address": "https://testnet-rest.deardoge.org"
      }
    ],
    "grpc": [
      {
        "address": "testnet-grpc.deardoge.org:443"
      }
    ]
  },
  "explorers": [
    {
      "kind": "Dear Doge Ping Pub",
      "url": "https://testnet-explorer.deardoge.org/deardoge",
      "txPage": "https://testnet-explorer.deardoge.org/deardoge/tx/${txHash}"
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/testnets/kyvedevnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chainName": "kyvedevnet",
  "chainType": "cosmos",
  "chainId": "korellia-2",
  "prettyName": "KYVE Korellia",
  "networkType": "devnet",
  "bech32Prefix": "kyve",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "tkyve",
        "fixedMinGasPrice": 0
      }
    ]
  },
  "codebase": {

  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.korellia.kyve.network"
      }
    ],
    "rest": [
      {
        "address": "https://api.korellia.kyve.network"
      }
    ]
  },
  "explorers": [
    {
      "kind": "KYVE Explorer",
      "url": "https://explorer.kyve.network/korellia",
      "txPage": "https://explorer.kyve.network/korellia/tx/${txHash}",
      "accountPage": "https://explorer.kyve.network/korellia/account/${accountAddress}"
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/persistence/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "persistence",
  "chainType": "cosmos",
  "chainId": "core-1",
  "prettyName": "Persistence",
  "networkType": "mainnet",
  "website": "https://persistence.one/",
  "bech32Prefix": "persistence",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "uxprt",
        "fixedMinGasPrice": 0,
        "lowGasPrice": 0,
        "averageGasPrice": 0.025,
        "highGasPrice": 0.04
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uxprt"
      }
    ],
    "lockDuration": {
      "time": "1814400s"
    }
  },
  "codebase": {
    "sdk": {
      "type": "cosmos",
      "repo": "https://github.com/cosmos/cosmos-sdk",
      "version": "v0.53.4",
      "tag": "v0.53.4"
    },
    "cosmwasm": {
      "version": "v0.60.2",
      "path": "$HOME/.persistenceCore/wasm",
      "enabled": true
    }
  },
  "description": "Persistence is an app chain for Liquid Staking powering an ecosystem of DeFi applications focused on unlocking the liquidity of staked assets.",
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.core.persistence.one"
      },
      {
        "address": "https://persistence.rpc.m.stavr.tech"
      },
      {
        "address": "https://persistence-rpc.polkachu.com"
      },
      {
        "address": "https://persistence-rpc.kleomedes.network"
      },
      {
        "address": "https://rpc-persistence.architectnodes.com"
      },
      {
        "address": "https://rpc-persistence.cosmos-spaces.cloud"
      },
      {
        "address": "https://persistence-mainnet-rpc.cosmonautstakes.com"
      },
      {
        "address": "https://persistence.rpc.quantnode.xyz"
      },
      {
        "address": "https://persistence-rpc.zenscape.one"
      },
      {
        "address": "https://persistence-mainnet-rpc.autostake.com:443"
      },
      {
        "address": "https://persistence-rpc.stakeandrelax.net"
      },
      {
        "address": "https://rpc.persistence.posthuman.digital:443"
      },
      {
        "address": "https://rpc-persistence-01.stakeflow.io"
      },
      {
        "address": "https://persistence-rpc.publicnode.com:443"
      },
      {
        "address": "https://persistence-rpc.highstakes.ch"
      },
      {
        "address": "https://persistence-rpc.stakeandrelax.net"
      },
      {
        "address": "https://rpc.persistence.validatus.com"
      },
      {
        "address": "https://public.stakewolle.com/cosmos/persistence/rpc"
      },
      {
        "address": "https://xprt-rpc.antrixy.org/"
      },
      {
        "address": "https://persistence-rpc.stake-town.com"
      },
      {
        "address": "https://persistence.api.pocket.network"
      }
    ],
    "rest": [
      {
        "address": "https://rest.core.persistence.one"
      },
      {
        "address": "https://persistence.api.m.stavr.tech"
      },
      {
        "address": "https://persistence-api.polkachu.com"
      },
      {
        "address": "https://api-persistence.cosmos-spaces.cloud"
      },
      {
        "address": "https://persistence-api.kleomedes.network"
      },
      {
        "address": "https://rest-persistence.architectnodes.com"
      },
      {
        "address": "https://persistence-mainnet-lcd.autostake.com:443"
      },
      {
        "address": "https://persistence-mainnet-rest.cosmonautstakes.com"
      },
      {
        "address": "https://persistence.lcd.quantnode.xyz"
      },
      {
        "address": "https://persistence-rest.zenscape.one"
      },
      {
        "address": "https://persistence-api.stakeandrelax.net"
      },
      {
        "address": "https://rest.persistence.posthuman.digital:443"
      },
      {
        "address": "https://api-persistence-01.stakeflow.io"
      },
      {
        "address": "https://persistence-rest.publicnode.com"
      },
      {
        "address": "https://persistence-api.highstakes.ch"
      },
      {
        "address": "https://persistence-api.stakeandrelax.net"
      },
      {
        "address": "https://api.persistence.validatus.com"
      },
      {
        "address": "https://public.stakewolle.com/cosmos/persistence/rest"
      },
      {
        "address": "https://xprt-rest.antrixy.org/"
      },
      {
        "address": "https://persistence-api.stake-town.com"
      },
      {
        "address": "https://persistence.api.pocket.network"
      }
    ],
    "grpc": [
      {
        "address": "grpc.core.persistence.one:443"
      },
      {
        "address": "persistence.grpc.m.stavr.tech:410"
      },
      {
        "address": "persistence-grpc.polkachu.com:15490"
      },
      {
        "address": "persistence-mainnet-grpc.autostake.com:443"
      },
      {
        "address": "grpc.persistence.posthuman.digital:80"
      },
      {
        "address": "grpc-persistence.cosmos-spaces.cloud:1180"
      },
      {
        "address": "141.95.33.97:9090"
      },
      {
        "address": "grpc-persistence-01.stakeflow.io:49090"
      },
      {
        "address": "persistence-grpc.w3coins.io:15490"
      },
      {
        "address": "persistence-grpc.publicnode.com:443"
      },
      {
        "address": "persistence-grpc.stakeandrelax.net:15490"
      },
      {
        "address": "grpc.persistence.validatus.com:443"
      },
      {
        "address": "https://xprt-grpc.antrixy.org/"
      },
      {
        "address": "persistence-grpc.stake-town.com:443"
      },
      {
        "address": "persistence.grpc.quantnode.xyz:22990"
      }
    ]
  },
  "explorers": [
    {
      "kind": "mintscan",
      "url": "https://www.mintscan.io/persistence",
      "txPage": "https://www.mintscan.io/persistence/transactions/${txHash}",
      "accountPage": "https://www.mintscan.io/persistence/accounts/${accountAddress}"
    },
    {
      "kind": "ezstaking",
      "url": "https://ezstaking.app/persistence",
      "txPage": "https://ezstaking.app/persistence/txs/${txHash}",
      "accountPage": "https://ezstaking.app/persistence/account/${accountAddress}"
    },
    {
      "kind": "ping.pub",
      "url": "https://ping.pub/persistence",
      "txPage": "https://ping.pub/persistence/tx/${txHash}"
    },
    {
      "kind": "🔥STAVR🔥",
      "url": "https://explorer.stavr.tech/Persistence-Mainnet",
      "txPage": "https://explorer.stavr.tech/Persistence-Mainnet/tx/${txHash}"
    },
    {
      "kind": "staking-explorer.com",
      "url": "https://staking-explorer.com/explorer/persistence",
      "txPage": "https://staking-explorer.com/transaction.php?chain=persistence&tx=${txHash}",
      "accountPage": "https://staking-explorer.com/account.php?chain=persistence&addr=${accountAddress}"
    },
    {
      "kind": "atomscan",
      "url": "https://atomscan.com/persistence",
      "txPage": "https://atomscan.com/persistence/transactions/${txHash}",
      "accountPage": "https://atomscan.com/persistence/accounts/${accountAddress}"
    },
    {
      "kind": "Stakeflow",
      "url": "https://stakeflow.io/persistence",
      "accountPage": "https://stakeflow.io/persistence/accounts/${accountAddress}"
    },
    {
      "kind": "Valopers",
      "url": "https://persistence.valopers.com/",
      "txPage": "https://persistence.valopers.com/transactions/${txHash}",
      "accountPage": "https://persistence.valopers.com/account/${accountAddress}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/persistence/images/xprt.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/persistence/images/xprt.svg"
    }
  ]
}
