=== chain-registry/chain-registry/registries/minimal/chain.schema.json
{
  "$id": "https://sikka.tech/chain.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Chain",
  "description": "Chain.json is a metadata file that contains information about a blockchain.",
  "type": "object",
  "required": [
    "$schema",
    "chainName",
    "chainType"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "pattern": "^(\\.\\./)+chain\\.schema\\.json$"
    },
    "website": {
      "type": "string",
      "minLength": 1,
      "format": "uri"
    },
    "slip44": {
      "type": "number"
    },
    "fees": {
      "type": "object",
      "required": [
        "feeTokens"
      ],
      "properties": {
        "feeTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/feeToken"
          }
        }
      },
      "additionalProperties": false
    },
    "staking": {
      "type": "object",
      "required": [
        "stakingTokens"
      ],
      "properties": {
        "stakingTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/stakingToken"
          }
        },
        "lockDuration": {
          "type": "object",
          "properties": {
            "blocks": {
              "type": "number",
              "description": "The number of blocks for which the staked tokens are locked."
            },
            "time": {
              "type": "string",
              "minLength": 1,
              "description": "The approximate time for which the staked tokens are locked."
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "codebase": {
      "type": "object",
      "properties": {
        "tag": {
          "$ref": "#/$defs/tag"
        },
        "language": {
          "$ref": "#/$defs/language"
        },
        "sdk": {
          "$ref": "#/$defs/sdk"
        },
        "cosmwasm": {
          "$ref": "#/$defs/cosmwasm"
        },
        "ibc": {
          "$ref": "#/$defs/ibc"
        }
      },
      "additionalProperties": false
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "png": {
            "type": "string",
            "minLength": 1,
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
          },
          "svg": {
            "type": "string",
            "minLength": 1,
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
          },
          "theme": {
            "type": "object",
            "properties": {
              "circle": {
                "type": "boolean"
              },
              "darkMode": {
                "type": "boolean"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          },
          "imageSync": {
            "$ref": "#/$defs/pointer"
          }
        },
        "anyOf": [
          {
            "required": [
              "png"
            ]
          },
          {
            "required": [
              "svg"
            ]
          }
        ],
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "maxLength": 3000
    },
    "apis": {
      "type": "object",
      "properties": {
        "rpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "rest": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "wss": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpcWeb": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "evmHttpJsonrpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        }
      },
      "additionalProperties": false
    },
    "snapshots": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/snapshot"
      }
    },
    "explorers": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/explorer"
      }
    },
    "keywords": {
      "type": "array",
      "maxContains": 20,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "chainName": {
      "type": "string",
      "minLength": 1,
      "pattern": "[a-z0-9]+"
    },
    "chainType": {
      "type": "string",
      "minLength": 1,
      "enum": [
        "cosmos",
        "eip155",
        "bip122",
        "polkadot",
        "solana",
        "algorand",
        "arweave",
        "ergo",
        "fil",
        "hedera",
        "monero",
        "reef",
        "stacks",
        "starknet",
        "stellar",
        "tezos",
        "vechain",
        "waves",
        "xrpl",
        "unknown"
      ],
      "description": "The 'type' of chain as the corresponding CAIP-2 Namespace value. E.G., 'cosmos' or 'eip155'. Namespaces cna be found here: https://github.com/ChainAgnostic/namespaces/tree/main."
    },
    "chainId": {
      "type": "string",
      "minLength": 1
    },
    "preForkChainName": {
      "type": "string",
      "minLength": 1,
      "pattern": "[a-z0-9]+"
    },
    "prettyName": {
      "type": "string",
      "minLength": 1
    },
    "networkType": {
      "enum": [
        "mainnet",
        "testnet",
        "devnet"
      ]
    },
    "bech32Prefix": {
      "type": "string",
      "minLength": 1,
      "description": "The default prefix for the human-readable part of addresses that identifies the coin type. Must be registered with SLIP-0173. E.g., 'cosmos'"
    },
    "nodeHome": {
      "type": "string",
      "minLength": 1
    },
    "keyAlgos": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "secp256k1",
          "ethsecp256k1",
          "ed25519",
          "sr25519",
          "bn254"
        ],
        "uniqueItems": true
      }
    },
    "extraCodecs": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "enum": [
          "ethermint",
          "injective"
        ],
        "uniqueItems": true
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "endpoint": {
      "type": "object",
      "required": [
        "address"
      ],
      "properties": {
        "address": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "snapshot": {
      "type": "object",
      "required": [
        "provider",
        "url"
      ],
      "properties": {
        "provider": {
          "type": "string",
          "minLength": 1
        },
        "url": {
          "type": "string",
          "minLength": 1
        },
        "type": {
          "type": "string",
          "enum": [
            "pruned",
            "archive"
          ]
        },
        "frequency": {
          "type": "string",
          "minLength": 1
        },
        "compression": {
          "type": "string",
          "enum": [
            "lz4",
            "zstd",
            "gzip",
            "tar",
            "none"
          ]
        },
        "latestUrl": {
          "type": "string",
          "minLength": 1
        },
        "dbBackend": {
          "type": "string",
          "enum": [
            "goleveldb",
            "pebbledb"
          ]
        },
        "checksumAvailable": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "explorer": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "minLength": 1
        },
        "url": {
          "type": "string",
          "minLength": 1
        },
        "txPage": {
          "type": "string",
          "minLength": 1
        },
        "accountPage": {
          "type": "string",
          "minLength": 1
        },
        "validatorPage": {
          "type": "string",
          "minLength": 1
        },
        "proposalPage": {
          "type": "string",
          "minLength": 1
        },
        "blockPage": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "repo": {
      "type": "string",
      "format": "uri",
      "minLength": 1,
      "description": "URL of the code repository."
    },
    "version": {
      "type": "string",
      "minLength": 1,
      "pattern": "^v?\\d+(\\.\\d+){0,2}$",
      "description": "Simple version string (e.g., 'v1.0.0')."
    },
    "tag": {
      "type": "string",
      "minLength": 1,
      "pattern": "^[A-Za-z0-9._/@-]+$",
      "description": "Git Upgrade Tag"
    },
    "sdk": {
      "type": "object",
      "required": [
        "type"
      ],
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "cosmos",
            "penumbra",
            "other"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        }
      }
    },
    "ibc": {
      "type": "object",
      "required": [
        "type"
      ],
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "go",
            "rust",
            "other"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        },
        "icsEnabled": {
          "type": "array",
          "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
          "items": {
            "type": "string",
            "minLength": 1,
            "description": "IBC app or ICS standard.",
            "enum": [
              "ics20-1",
              "ics27-1",
              "mauth"
            ]
          }
        }
      }
    },
    "cosmwasm": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        },
        "enabled": {
          "type": "boolean"
        },
        "path": {
          "type": "string",
          "minLength": 1,
          "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
          "pattern": "^\\$HOME.*$"
        }
      }
    },
    "consensus": {
      "type": "object",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "tendermint",
            "cometbft",
            "sei-tendermint",
            "cometbls"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        }
      },
      "additionalProperties": false
    },
    "language": {
      "type": "object",
      "required": [
        "type"
      ],
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "minLength": 1,
          "enum": [
            "go",
            "rust",
            "solidity",
            "other"
          ]
        },
        "version": {
          "$ref": "#/$defs/version"
        },
        "repo": {
          "$ref": "#/$defs/repo"
        },
        "tag": {
          "$ref": "#/$defs/tag"
        }
      }
    },
    "binaries": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "linux/amd64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "linux/arm64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "darwin/amd64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "darwin/arm64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "windows/amd64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "windows/arm64": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        }
      }
    },
    "pointer": {
      "type": "object",
      "description": "The (primary) key used to identify an object within the Chain Registry.",
      "required": [
        "chainName"
      ],
      "properties": {
        "chainName": {
          "type": "string",
          "minLength": 1,
          "description": "The chain name or platform from which the object resides. E.g., 'cosmoshub', 'ethereum', 'forex', or 'nasdaq'"
        },
        "baseDenom": {
          "type": "string",
          "minLength": 1,
          "description": "The base denom of the asset from which the object originates. E.g., when describing ATOM from Cosmos Hub, specify 'uatom', NOT 'atom' nor 'ATOM'; base units are unique per platform."
        }
      },
      "additionalProperties": false
    },
    "feeToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string",
          "minLength": 1
        },
        "fixedMinGasPrice": {
          "type": "number"
        },
        "lowGasPrice": {
          "type": "number"
        },
        "averageGasPrice": {
          "type": "number"
        },
        "highGasPrice": {
          "type": "number"
        },
        "gasCosts": {
          "type": "object",
          "properties": {
            "cosmosSend": {
              "type": "number"
            },
            "ibcTransfer": {
              "type": "number"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "stakingToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "chain_type": {
            "const": "cosmos"
          }
        }
      },
      "then": {
        "required": [
          "bech32_prefix"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "chain_type": {
            "enum": [
              "cosmos",
              "eip155"
            ]
          }
        }
      },
      "then": {
        "required": [
          "chain_id"
        ]
      }
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/safrochain/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "safrochain",
  "chainType": "cosmos",
  "networkType": "mainnet",
  "website": "https://safrochain.com",
  "prettyName": "Safrochain",
  "chainId": "safrochain-1",
  "bech32Prefix": "addr_safro",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "usaf",
        "fixedMinGasPrice": 0.05,
        "lowGasPrice": 0.05,
        "averageGasPrice": 0.0625,
        "highGasPrice": 0.075
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "usaf"
      }
    ]
  },
  "codebase": {
    "sdk": {
      "type": "cosmos",
      "version": "0.50.14"
    }
  },
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/safrochain/images/saf.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/safrochain/images/saf.svg"
    }
  ],
  "description": "Safrochain is building a mobile-first, mobile-money-powered blockchain that connects blockchain infrastructure to mobile money networks—turning mobile wallets into gateways to stablecoins, programmable finance, cross-border settlement, and lower-cost interoperable transfers across operators and borders.",
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.safrochain.network"
      },
      {
        "address": "https://rpc1.safrochain.network"
      },
      {
        "address": "https://rpc2.safrochain.network"
      }
    ],
    "rest": [
      {
        "address": "https://api.safrochain.network"
      },
      {
        "address": "https://api1.safrochain.network"
      },
      {
        "address": "https://api2.safrochain.network"
      }
    ],
    "grpc": [
      {
        "address": "https://grpc.safrochain.network:443"
      },
      {
        "address": "https://grpc1.safrochain.network:443"
      },
      {
        "address": "https://grpc2.safrochain.network:443"
      }
    ],
    "grpcWeb": [
      {
        "address": "https://grpc-web.safrochain.network"
      }
    ],
    "wss": [
      {
        "address": "wss://rpc.safrochain.network/websocket"
      },
      {
        "address": "wss://rpc1.safrochain.network/websocket"
      }
    ]
  },
  "explorers": [
    {
      "kind": "safroexplorer",
      "url": "https://explorer.safrochain.com/",
      "txPage": "https://explorer.safrochain.com/tx/${txHash}",
      "accountPage": "https://explorer.safrochain.com/address/${accountAddress}",
      "validatorPage": "https://explorer.safrochain.com/validator/${validatorAddress}"
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/testnets/manifesttestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chainName": "manifesttestnet",
  "networkType": "testnet",
  "website": "https://manifestai.org/",
  "prettyName": "Manifest Testnet",
  "chainId": "manifest-ledger-testnet",
  "chainType": "cosmos",
  "bech32Prefix": "manifest",
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "umfx",
        "fixedMinGasPrice": 1,
        "lowGasPrice": 1.05,
        "averageGasPrice": 1.1,
        "highGasPrice": 3
      },
      {
        "denom": "factory/manifest1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfmy9qj/upwr",
        "fixedMinGasPrice": 0.37,
        "lowGasPrice": 0.4,
        "averageGasPrice": 0.5,
        "highGasPrice": 1
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "upoa"
      }
    ]
  },
  "codebase": {

  },
  "apis": {
    "rpc": [
      {
        "address": "https://nodes.liftedinit.tech/manifest/testnet/rpc"
      }
    ],
    "rest": [
      {
        "address": "https://nodes.liftedinit.tech/manifest/testnet/api"
      }
    ],
    "grpc": [
      {
        "address": "https://manifest-testnet-grpc.liftedinit.tech"
      }
    ]
  },
  "explorers": [
    {
      "kind": "Default Explorer",
      "url": "https://testnet.manifest.explorers.guru/",
      "txPage": "https://testnet.manifest.explorers.guru/transaction/${txHash}",
      "accountPage": "https://testnet.manifest.explorers.guru/account/${accountAddress}"
    }
  ],
  "images": [
    {
      "imageSync": {
        "chainName": "manifesttestnet"
      },
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/manifest/images/manifest.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/manifest/images/manifest.svg"
    }
  ]
}

=== chain-registry/chain-registry/registries/minimal/aura1/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "aura1",
  "networkType": "mainnet",
  "website": "https://aura.network/",
  "prettyName": "Aura Network",
  "chainType": "cosmos",
  "chainId": "xstaxy-1",
  "bech32Prefix": "aura",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "uaura",
        "fixedMinGasPrice": 0.001,
        "lowGasPrice": 0.001,
        "averageGasPrice": 0.002,
        "highGasPrice": 0.0025
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uaura"
      }
    ],
    "lockDuration": {
      "time": "1209600s"
    }
  },
  "codebase": {
    "sdk": {
      "type": "cosmos",
      "version": "0.47.5"
    },
    "cosmwasm": {
      "version": "0.42.0",
      "enabled": true
    }
  },
  "apis": {
    "rpc": [
      {
        "address": "https://rpc.aura.network/"
      },
      {
        "address": "https://m-aura.rpc.utsa.tech"
      },
      {
        "address": "http://aura.rpc.m.stavr.tech:11047"
      },
      {
        "address": "https://aura-rpc.ramuchi.tech"
      },
      {
        "address": "https://aura.rpc.kjnodes.com"
      },
      {
        "address": "https://mainnet-aura-rpc.konsortech.xyz"
      },
      {
        "address": "https://rpc.lavenderfive.com:443/aura"
      },
      {
        "address": "https://aura-rpc.staketab.org:443"
      },
      {
        "address": "https://rpc.aura.safeblock.space"
      },
      {
        "address": "https://rpc.aura.silentvalidator.com"
      },
      {
        "address": "https://rpc-aura.mms.team"
      },
      {
        "address": "https://aura-rpc.stake-town.com"
      },
      {
        "address": "https://aura-rpc.palamar.io"
      },
      {
        "address": "https://aura.rpc.srv.stakr.space"
      },
      {
        "address": "https://aura-rpc.highstakes.ch"
      },
      {
        "address": "https://aura-rpc.noders.services"
      }
    ],
    "rest": [
      {
        "address": "https://lcd.aura.network/"
      },
      {
        "address": "https://m-aura.api.utsa.tech"
      },
      {
        "address": "https://aura.api.m.stavr.tech"
      },
      {
        "address": "https://aura-api.ramuchi.tech"
      },
      {
        "address": "https://aura.api.kjnodes.com"
      },
      {
        "address": "https://mainnet-aura-api.konsortech.xyz"
      },
      {
        "address": "https://rest.lavenderfive.com:443/aura"
      },
      {
        "address": "https://aura-rest.staketab.org"
      },
      {
        "address": "https://api.aura.safeblock.space"
      },
      {
        "address": "https://api.aura.silentvalidator.com"
      },
      {
        "address": "https://api-aura.mms.team"
      },
      {
        "address": "https://aura-api.stake-town.com"
      },
      {
        "address": "https://aura-api.palamar.io"
      },
      {
        "address": "https://aura.api.srv.stakr.space"
      },
      {
        "address": "https://aura-api.highstakes.ch"
      },
      {
        "address": "https://aura-api.noders.services"
      }
    ],
    "grpc": [
      {
        "address": "https://grpc.aura.network"
      },
      {
        "address": "auranetwork-mainnet-grpc.autostake.com:443"
      },
      {
        "address": "https://aura-grpc.ramuchi.tech:15000"
      },
      {
        "address": "http://aura.grpc.m.stavr.tech:9901"
      },
      {
        "address": "aura.grpc.kjnodes.com:11790"
      },
      {
        "address": "aura.lavenderfive.com:443"
      },
      {
        "address": "services.staketab.com:9021"
      },
      {
        "address": "grpc.aura.silentvalidator.com:443"
      },
      {
        "address": "grpc-aura.mms.team:443"
      },
      {
        "address": "aura-grpc.stake-town.com:443"
      },
      {
        "address": "grpc.aura.safeblock.space:9090"
      },
      {
        "address": "aura-grpc.palamar.io:443"
      },
      {
        "address": "aura.grpc.srv.stakr.space:19090"
      },
      {
        "address": "aura-grpc.noders.services:17090"
      }
    ]
  },
  "explorers": [
    {
      "kind": "aurascan",
      "url": "https://aurascan.io",
      "txPage": "https://aurascan.io/transaction/${txHash}",
      "accountPage": "https://aurascan.io/account/${accountAddress}"
    },
    {
      "kind": "𝐥𝐞𝐬𝐧𝐢𝐤 | 𝐔𝐓𝐒𝐀 Explorer",
      "url": "https://exp.utsa.tech/aura",
      "txPage": "https://exp.utsa.tech/aura/tx/${txHash}",
      "accountPage": "https://exp.utsa.tech/aura/account/${accountAddress}"
    },
    {
      "kind": "🔥STAVR🔥 Explorer",
      "url": "https://explorer.stavr.tech/Aura-Mainnet",
      "txPage": "https://explorer.stavr.tech/aura-mainnet/tx/${txHash}",
      "accountPage": "https://explorer.stavr.tech/aura-mainnet/account/${accountAddress}"
    },
    {
      "kind": "NodeStake Explorer",
      "url": "https://explorer.nodestake.org/aura",
      "txPage": "https://explorer.nodestake.org/aura/tx/${txHash}",
      "accountPage": "https://explorer.nodestake.org/aura/account/${accountAddress}"
    },
    {
      "kind": "TC Network",
      "url": "https://explorer.tcnetwork.io/aura",
      "txPage": "https://explorer.tcnetwork.io/aura/transaction/${txHash}",
      "accountPage": "https://explorer.tcnetwork.io/aura/account/${accountAddress}"
    },
    {
      "kind": "Stake-Take",
      "url": "https://explorer.stake-take.com/aura",
      "txPage": "https://explorer.stake-take.com/aura/tx/${txHash}",
      "accountPage": "https://explorer.stake-take.com/aura/account/${accountAddress}"
    },
    {
      "kind": "Safe Block",
      "url": "https://explorer.safeblock.space/aura",
      "txPage": "https://explorer.safeblock.space/aura/tx/${txHash}",
      "accountPage": "https://explorer.safeblock.space/aura/account/${accountAddress}"
    },
    {
      "kind": "STAKR.space explorer",
      "url": "https://explorer.stakr.space/aura/",
      "txPage": "https://explorer.stakr.space/aura/tx/${txHash}",
      "accountPage": "https://explorer.stakr.space/aura/account/${accountAddress}"
    }
  ],
  "images": [
    {
      "imageSync": {
        "chainName": "aura"
      },
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/aura/images/Aura-logo-2.2.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/aura/images/Aura-logo-2.2.svg"
    }
  ]
}
