=== chain-registry/chain-registry/registries/full/chain.schema.json
{
  "$id": "https://sikka.tech/chain.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Chain",
  "description": "Chain.json is a metadata file that contains information about a blockchain.",
  "type": "object",
  "required": [
    "chainName",
    "chainId",
    "bech32Prefix"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^(\\.\\./)+chain\\.schema\\.json$"
    },
    "website": {
      "type": "string",
      "format": "uri"
    },
    "status": {
      "enum": [
        "live",
        "upcoming",
        "killed"
      ]
    },
    "slip44": {
      "type": "number"
    },
    "fees": {
      "type": "object",
      "required": [
        "feeTokens"
      ],
      "properties": {
        "feeTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/feeToken"
          }
        }
      },
      "additionalProperties": false
    },
    "staking": {
      "type": "object",
      "required": [
        "stakingTokens"
      ],
      "properties": {
        "stakingTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/stakingToken"
          }
        },
        "lockDuration": {
          "type": "object",
          "properties": {
            "blocks": {
              "type": "number",
              "description": "The number of blocks for which the staked tokens are locked."
            },
            "time": {
              "type": "string",
              "description": "The approximate time for which the staked tokens are locked."
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "codebase": {
      "type": "object",
      "properties": {
        "binaries": {
          "type": "object",
          "properties": {
            "linux/amd64": {
              "type": "string",
              "format": "uri"
            },
            "linux/arm64": {
              "type": "string",
              "format": "uri"
            },
            "darwin/amd64": {
              "type": "string",
              "format": "uri"
            },
            "darwin/arm64": {
              "type": "string",
              "format": "uri"
            },
            "windows/amd64": {
              "type": "string",
              "format": "uri"
            },
            "windows/arm64": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "consensus": {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "tendermint",
                "cometbft",
                "sei-tendermint"
              ]
            },
            "version": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "genesis": {
          "type": "object",
          "required": [
            "genesisUrl"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "genesisUrl": {
              "type": "string",
              "format": "uri"
            },
            "icsCcvUrl": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "versions": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name"
            ],
            "properties": {
              "name": {
                "type": "string",
                "description": "Official Upgrade Name"
              },
              "tag": {
                "type": "string",
                "description": "Git Upgrade Tag"
              },
              "height": {
                "type": "number",
                "description": "Block Height"
              },
              "proposal": {
                "type": "number",
                "description": "Proposal that will officially signal community acceptance of the upgrade."
              },
              "consensus": {
                "type": "object",
                "required": [
                  "type"
                ],
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "tendermint",
                      "cometbft",
                      "sei-tendermint"
                    ]
                  },
                  "version": {
                    "type": "string"
                  }
                },
                "additionalProperties": false
              },
              "binaries": {
                "type": "object",
                "properties": {
                  "linux/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "linux/arm64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "darwin/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "darwin/arm64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "windows/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "windows/arm64": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "additionalProperties": false
              },
              "previousVersionName": {
                "type": "string",
                "description": "[Optional] Name of the previous version"
              },
              "nextVersionName": {
                "type": "string",
                "description": "[Optional] Name of the following version"
              },
              "recommendedVersion": {
                "type": "string"
              },
              "goVersion": {
                "type": "string",
                "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
                "description": "Minimum accepted go version to build the binary."
              },
              "compatibleVersions": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "cosmosSdkVersion": {
                "type": "string"
              },
              "cosmwasmVersion": {
                "type": "string"
              },
              "cosmwasmEnabled": {
                "type": "boolean"
              },
              "cosmwasmPath": {
                "type": "string",
                "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
                "pattern": "^\\$HOME.*$"
              },
              "ibcGoVersion": {
                "type": "string"
              },
              "icsEnabled": {
                "type": "array",
                "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
                "items": {
                  "type": "string",
                  "description": "IBC app or ICS standard.",
                  "enum": [
                    "ics20-1",
                    "ics27-1",
                    "mauth"
                  ]
                }
              }
            },
            "additionalProperties": false
          }
        },
        "gitRepo": {
          "type": "string",
          "format": "uri"
        },
        "recommendedVersion": {
          "type": "string"
        },
        "goVersion": {
          "type": "string",
          "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
          "description": "Minimum accepted go version to build the binary."
        },
        "compatibleVersions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cosmosSdkVersion": {
          "type": "string"
        },
        "cosmwasmVersion": {
          "type": "string"
        },
        "cosmwasmEnabled": {
          "type": "boolean"
        },
        "cosmwasmPath": {
          "type": "string",
          "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
          "pattern": "^\\$HOME.*$"
        },
        "ibcGoVersion": {
          "type": "string"
        },
        "icsEnabled": {
          "type": "array",
          "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
          "items": {
            "type": "string",
            "description": "IBC app or ICS standard.",
            "enum": [
              "ics20-1",
              "ics27-1",
              "mauth"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "png": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
          },
          "svg": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
          },
          "theme": {
            "type": "object",
            "properties": {
              "circle": {
                "type": "boolean"
              },
              "primaryColorHex": {
                "type": "string",
                "pattern": "^#[0-9a-fA-F]{6}$"
              },
              "darkMode": {
                "type": "boolean"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          },
          "layout": {
            "type": "string",
            "enum": [
              "logo",
              "logomark",
              "logotype"
            ],
            "description": "logomark == icon only; logotype == text only; logo == icon + text."
          },
          "imageSync": {
            "$ref": "#/$defs/pointer"
          },
          "textPosition": {
            "type": "string",
            "enum": [
              "top",
              "bottom",
              "left",
              "right",
              "integrated"
            ],
            "description": "Indicates in which position the text is placed, in case the layout is 'icon' type, it's required only in this case."
          }
        },
        "if": {
          "properties": {
            "layout": {
              "const": "logo"
            }
          },
          "required": [
            "layout"
          ]
        },
        "then": {
          "required": [
            "text_position"
          ]
        },
        "anyOf": [
          {
            "required": [
              "png"
            ]
          },
          {
            "required": [
              "svg"
            ]
          }
        ],
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string",
      "maxLength": 3000
    },
    "peers": {
      "type": "object",
      "properties": {
        "seeds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/peer"
          }
        },
        "persistentPeers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/peer"
          }
        }
      },
      "additionalProperties": false
    },
    "apis": {
      "type": "object",
      "properties": {
        "rpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "rest": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "wss": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpcWeb": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "evmHttpJsonrpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        }
      },
      "additionalProperties": false
    },
    "explorers": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/explorer"
      }
    },
    "keywords": {
      "type": "array",
      "maxContains": 20,
      "items": {
        "type": "string"
      }
    },
    "chainName": {
      "type": "string",
      "pattern": "[a-z0-9]+"
    },
    "chainId": {
      "type": "string"
    },
    "preForkChainName": {
      "type": "string",
      "pattern": "[a-z0-9]+"
    },
    "prettyName": {
      "type": "string"
    },
    "updateLink": {
      "type": "string",
      "format": "uri"
    },
    "networkType": {
      "enum": [
        "mainnet",
        "testnet",
        "devnet"
      ]
    },
    "bech32Prefix": {
      "type": "string",
      "description": "The default prefix for the human-readable part of addresses that identifies the coin type. Must be registered with SLIP-0173. E.g., 'cosmos'"
    },
    "bech32Config": {
      "type": "object",
      "description": "Used to override the bech32_prefix for specific uses.",
      "properties": {
        "bech32PrefixAccAddr": {
          "type": "string",
          "description": "e.g., 'cosmos'"
        },
        "bech32PrefixAccPub": {
          "type": "string",
          "description": "e.g., 'cosmospub'"
        },
        "bech32PrefixValAddr": {
          "type": "string",
          "description": "e.g., 'cosmosvaloper'"
        },
        "bech32PrefixValPub": {
          "type": "string",
          "description": "e.g., 'cosmosvaloperpub'"
        },
        "bech32PrefixConsAddr": {
          "type": "string",
          "description": "e.g., 'cosmosvalcons'"
        },
        "bech32PrefixConsPub": {
          "type": "string",
          "description": "e.g., 'cosmosvalconspub'"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "daemonName": {
      "type": "string"
    },
    "nodeHome": {
      "type": "string"
    },
    "keyAlgos": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "secp256k1",
          "ethsecp256k1",
          "ed25519",
          "sr25519",
          "bn254"
        ],
        "uniqueItems": true
      }
    },
    "alternativeSlip44s": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "logoURIs": {
      "type": "object",
      "properties": {
        "png": {
          "type": "string",
          "format": "uri-reference",
          "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
        },
        "svg": {
          "type": "string",
          "format": "uri-reference",
          "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
        }
      },
      "additionalProperties": false
    },
    "extraCodecs": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ethermint",
          "injective"
        ],
        "uniqueItems": true
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "peer": {
      "type": "object",
      "required": [
        "id",
        "address"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "endpoint": {
      "type": "object",
      "required": [
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "archive": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "explorer": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "txPage": {
          "type": "string"
        },
        "accountPage": {
          "type": "string"
        },
        "validatorPage": {
          "type": "string"
        },
        "proposalPage": {
          "type": "string"
        },
        "blockPage": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "pointer": {
      "type": "object",
      "description": "The (primary) key used to identify an object within the Chain Registry.",
      "required": [
        "chainName"
      ],
      "properties": {
        "chainName": {
          "type": "string",
          "description": "The chain name or platform from which the object resides. E.g., 'cosmoshub', 'ethereum', 'forex', or 'nasdaq'"
        },
        "baseDenom": {
          "type": "string",
          "description": "The base denom of the asset from which the object originates. E.g., when describing ATOM from Cosmos Hub, specify 'uatom', NOT 'atom' nor 'ATOM'; base units are unique per platform."
        }
      },
      "additionalProperties": false
    },
    "feeToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        },
        "fixedMinGasPrice": {
          "type": "number"
        },
        "lowGasPrice": {
          "type": "number"
        },
        "averageGasPrice": {
          "type": "number"
        },
        "highGasPrice": {
          "type": "number"
        },
        "gasCosts": {
          "type": "object",
          "properties": {
            "cosmosSend": {
              "type": "number"
            },
            "ibcTransfer": {
              "type": "number"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "stakingToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}

=== chain-registry/chain-registry/registries/full/secretnetwork/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "secretnetwork",
  "status": "live",
  "networkType": "mainnet",
  "website": "https://scrt.network/",
  "prettyName": "Secret Network",
  "chainId": "secret-4",
  "bech32Prefix": "secret",
  "daemonName": "secretd",
  "nodeHome": "$HOME/.secretd",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 529,
  "alternativeSlip44s": [
    118
  ],
  "fees": {
    "feeTokens": [
      {
        "denom": "uscrt",
        "fixedMinGasPrice": 0.05,
        "lowGasPrice": 0.05,
        "averageGasPrice": 0.1,
        "highGasPrice": 0.25
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uscrt"
      }
    ]
  },
  "codebase": {
    "gitRepo": "https://github.com/scrtlabs/SecretNetwork",
    "recommendedVersion": "v1.12.1",
    "compatibleVersions": [
      "v1.12.1"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.12.1/secretnetwork_1.12.1_mainnet_goleveldb_amd64.deb"
    },
    "genesis": {
      "genesisUrl": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.2.0/genesis.json"
    },
    "versions": [
      {
        "name": "v1.2",
        "tag": "v1.2",
        "height": 0,
        "nextVersionName": "v1.3"
      },
      {
        "name": "v1.3",
        "tag": "v1.3",
        "height": 3343000,
        "nextVersionName": "v1.4"
      },
      {
        "name": "v1.4",
        "tag": "v1.4",
        "height": 5309200,
        "nextVersionName": "v1.5"
      },
      {
        "name": "v1.5",
        "tag": "v1.5",
        "height": 5941700,
        "nextVersionName": "v1.6"
      },
      {
        "name": "v1.6",
        "tag": "v1.6",
        "height": 6537300,
        "nextVersionName": "v1.7"
      },
      {
        "name": "v1.7",
        "tag": "v1.7.1",
        "height": 7719500,
        "nextVersionName": "v1.8"
      },
      {
        "name": "v1.8",
        "tag": "v1.8.0",
        "height": 7760000,
        "nextVersionName": "v1.9",
        "recommendedVersion": "v1.8.0",
        "compatibleVersions": [
          "v1.8.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.8.0/secretnetwork_1.8.0_mainnet_goleveldb_amd64.deb"
        }
      },
      {
        "name": "v1.9",
        "tag": "v1.9.0",
        "height": 8861800,
        "recommendedVersion": "v1.9.0",
        "compatibleVersions": [
          "v1.9.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.9.0/secretnetwork_1.9.0_mainnet_goleveldb_amd64.deb"
        }
      },
      {
        "name": "v1.9",
        "tag": "v1.9.2",
        "height": 8861815,
        "recommendedVersion": "v1.9.2",
        "compatibleVersions": [
          "v1.9.2"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.9.2/secretnetwork_1.9.2_mainnet_goleveldb_amd64.deb"
        },
        "nextVersionName": "v1.10"
      },
      {
        "name": "v1.10",
        "tag": "v1.10.0",
        "height": 10186400,
        "recommendedVersion": "v1.10.0",
        "compatibleVersions": [
          "v1.10.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.10.0/secretnetwork_1.10.0_mainnet_goleveldb_amd64.deb"
        },
        "nextVersionName": "v1.11"
      },
      {
        "name": "v1.11",
        "tag": "v1.11.0",
        "height": 10824000,
        "recommendedVersion": "v1.11.0",
        "compatibleVersions": [
          "v1.11.0"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.11.0/secretnetwork_1.11.0_mainnet_goleveldb_amd64.deb"
        },
        "nextVersionName": "v1.12"
      },
      {
        "name": "v1.12",
        "tag": "v1.12.1",
        "height": 11136666,
        "recommendedVersion": "v1.12.1",
        "compatibleVersions": [
          "v1.12.1"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/scrtlabs/SecretNetwork/releases/download/v1.12.1/secretnetwork_1.12.1_mainnet_goleveldb_amd64.deb"
        },
        "nextVersionName": ""
      }
    ]
  },
  "logoURIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/secretnetwork/images/scrt.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/secretnetwork/images/scrt.svg"
  },
  "description": "Secret Network is the first blockchain with customizable privacy. You get to choose what you share, with whom, and how. This protects users, and empowers developers to build a better Web3.",
  "peers": {
    "seeds": [
      {
        "id": "6fb7169f7630da9468bf7cc0bcbbed1eb9ed0d7b",
        "address": "scrt-seed-01.scrtlabs.com:26656",
        "provider": "SCRT Labs"
      },
      {
        "id": "ab6394e953e0b570bb1deeb5a8b387aa0dc6188a",
        "address": "scrt-seed-02.scrtlabs.com:26656",
        "provider": "SCRT Labs"
      },
      {
        "id": "9cdaa5856e0245ecd73bd464308fb990fbc53b57",
        "address": "scrt-seed-03.scrtlabs.com:26656",
        "provider": "SCRT Labs"
      },
      {
        "id": "20e1000e88125698264454a884812746c2eb4807",
        "address": "seeds.lavenderfive.com:17156",
        "provider": "Lavender.Five Nodes 🐝"
      },
      {
        "id": "c28827cb96c14c905b127b92065a3fb4cd77d7f6",
        "address": "seeds.whispernode.com:17156",
        "provider": "WhisperNode 🤐"
      },
      {
        "id": "5b0d6ef879fe1326045fa18d5bf767c5968704e6",
        "address": "secretnetwork-mainnet-seed.autostake.com:26656",
        "provider": "AutoStake 🛡️ Slash Protected"
      },
      {
        "id": "8542cd7e6bf9d260fef543bc49e59be5a3fa9074",
        "address": "seed.publicnode.com:26656",
        "provider": "Allnodes ⚡️ Nodes & Staking"
      }
    ],
    "persistentPeers": [
      {
        "id": "5b0d6ef879fe1326045fa18d5bf767c5968704e6",
        "address": "secretnetwork-mainnet-peer.autostake.com:26656",
        "provider": "AutoStake 🛡️ Slash Protected"
      }
    ]
  },
  "apis": {
    "grpcWeb": [
      {
        "address": "https://grpc.mainnet.secretsaturn.net",
        "provider": "🪐 𝕊ecret 𝕊aturn"
      }
    ],
    "rpc": [
      {
        "address": "https://scrt.public-rpc.com",
        "provider": "ANKR"
      },
      {
        "address": "https://secretnetwork-rpc.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes 🐝"
      },
      {
        "address": "https://1rpc.io/scrt-rpc",
        "provider": "1RPC - Automata Network"
      },
      {
        "address": "https://secretnetwork-rpc.highstakes.ch",
        "provider": "High Stakes 🇨🇭"
      },
      {
        "address": "https://rpc.mainnet.secretsaturn.net",
        "provider": "🪐 𝕊ecret 𝕊aturn"
      },
      {
        "address": "https://rpc-secret.01node.com",
        "provider": "01node"
      },
      {
        "address": "https://public.stakewolle.com/cosmos/secretnetwork/rpc",
        "provider": "Stakewolle"
      }
    ],
    "rest": [
      {
        "address": "https://secretnetwork-api.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes 🐝"
      },
      {
        "address": "http://secretnetwork-mainnet-lcd.autostake.com:1317",
        "provider": "AutoStake 🛡️ Slash Protected"
      },
      {
        "address": "https://1rpc.io/scrt-lcd",
        "provider": "1RPC - Automata Network"
      },
      {
        "address": "https://secretnetwork-api.highstakes.ch",
        "provider": "High Stakes 🇨🇭"
      },
      {
        "address": "https://lcd.mainnet.secretsaturn.net",
        "provider": "🪐 𝕊ecret 𝕊aturn"
      },
      {
        "address": "https://rest-secret.01node.com",
        "provider": "01node"
      },
      {
        "address": "https://public.stakewolle.com/cosmos/secretnetwork/rest",
        "provider": "Stakewolle"
      }
    ],
    "grpc": [
      {
        "address": "secretnetwork-grpc.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes 🐝"
      },
      {
        "address": "secretnetwork-mainnet-grpc.autostake.com:9090",
        "provider": "AutoStake 🛡️ Slash Protected"
      }
    ]
  },
  "explorers": [
    {
      "kind": "ezstaking",
      "url": "https://ezstaking.app/secretnetwork",
      "txPage": "https://ezstaking.app/secretnetwork/txs/${txHash}",
      "accountPage": "https://ezstaking.app/secretnetwork/account/${accountAddress}"
    },
    {
      "kind": "ping.pub",
      "url": "https://ping.pub/secret",
      "txPage": "https://ping.pub/secret/tx/${txHash}"
    },
    {
      "kind": "mintscan",
      "url": "https://www.mintscan.io/secret",
      "txPage": "https://www.mintscan.io/secret/transactions/${txHash}",
      "accountPage": "https://www.mintscan.io/secret/accounts/${accountAddress}"
    },
    {
      "kind": "atomscan",
      "url": "https://atomscan.com/secret-network",
      "txPage": "https://atomscan.com/secret-network/transactions/${txHash}",
      "accountPage": "https://atomscan.com/secret-network/accounts/${accountAddress}"
    },
    {
      "kind": "WhisperNode 🤐",
      "url": "https://mainnet.whispernode.com/secret",
      "txPage": "https://mainnet.whispernode.com/secret/tx/${txHash}",
      "accountPage": "https://mainnet.whispernode.com/secret/account/${accountAddress}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/secretnetwork/images/scrt.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/secretnetwork/images/scrt.svg",
      "theme": {
        "primaryColorHex": "#040404"
      }
    }
  ]
}
