=== chain-registry/chain-registry/registries/full/chain.schema.json
{
  "$id": "https://sikka.tech/chain.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Chain",
  "description": "Chain.json is a metadata file that contains information about a blockchain.",
  "type": "object",
  "required": [
    "chainName",
    "chainId",
    "bech32Prefix"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "pattern": "^(\\.\\./)+chain\\.schema\\.json$"
    },
    "website": {
      "type": "string",
      "format": "uri"
    },
    "status": {
      "enum": [
        "live",
        "upcoming",
        "killed"
      ]
    },
    "slip44": {
      "type": "number"
    },
    "fees": {
      "type": "object",
      "required": [
        "feeTokens"
      ],
      "properties": {
        "feeTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/feeToken"
          }
        }
      },
      "additionalProperties": false
    },
    "staking": {
      "type": "object",
      "required": [
        "stakingTokens"
      ],
      "properties": {
        "stakingTokens": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/stakingToken"
          }
        },
        "lockDuration": {
          "type": "object",
          "properties": {
            "blocks": {
              "type": "number",
              "description": "The number of blocks for which the staked tokens are locked."
            },
            "time": {
              "type": "string",
              "description": "The approximate time for which the staked tokens are locked."
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "codebase": {
      "type": "object",
      "properties": {
        "binaries": {
          "type": "object",
          "properties": {
            "linux/amd64": {
              "type": "string",
              "format": "uri"
            },
            "linux/arm64": {
              "type": "string",
              "format": "uri"
            },
            "darwin/amd64": {
              "type": "string",
              "format": "uri"
            },
            "darwin/arm64": {
              "type": "string",
              "format": "uri"
            },
            "windows/amd64": {
              "type": "string",
              "format": "uri"
            },
            "windows/arm64": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "consensus": {
          "type": "object",
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "tendermint",
                "cometbft",
                "sei-tendermint"
              ]
            },
            "version": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "genesis": {
          "type": "object",
          "required": [
            "genesisUrl"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "genesisUrl": {
              "type": "string",
              "format": "uri"
            },
            "icsCcvUrl": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "versions": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name"
            ],
            "properties": {
              "name": {
                "type": "string",
                "description": "Official Upgrade Name"
              },
              "tag": {
                "type": "string",
                "description": "Git Upgrade Tag"
              },
              "height": {
                "type": "number",
                "description": "Block Height"
              },
              "proposal": {
                "type": "number",
                "description": "Proposal that will officially signal community acceptance of the upgrade."
              },
              "consensus": {
                "type": "object",
                "required": [
                  "type"
                ],
                "properties": {
                  "type": {
                    "type": "string",
                    "enum": [
                      "tendermint",
                      "cometbft",
                      "sei-tendermint"
                    ]
                  },
                  "version": {
                    "type": "string"
                  }
                },
                "additionalProperties": false
              },
              "binaries": {
                "type": "object",
                "properties": {
                  "linux/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "linux/arm64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "darwin/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "darwin/arm64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "windows/amd64": {
                    "type": "string",
                    "format": "uri"
                  },
                  "windows/arm64": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "additionalProperties": false
              },
              "previousVersionName": {
                "type": "string",
                "description": "[Optional] Name of the previous version"
              },
              "nextVersionName": {
                "type": "string",
                "description": "[Optional] Name of the following version"
              },
              "recommendedVersion": {
                "type": "string"
              },
              "goVersion": {
                "type": "string",
                "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
                "description": "Minimum accepted go version to build the binary."
              },
              "compatibleVersions": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "cosmosSdkVersion": {
                "type": "string"
              },
              "cosmwasmVersion": {
                "type": "string"
              },
              "cosmwasmEnabled": {
                "type": "boolean"
              },
              "cosmwasmPath": {
                "type": "string",
                "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
                "pattern": "^\\$HOME.*$"
              },
              "ibcGoVersion": {
                "type": "string"
              },
              "icsEnabled": {
                "type": "array",
                "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
                "items": {
                  "type": "string",
                  "description": "IBC app or ICS standard.",
                  "enum": [
                    "ics20-1",
                    "ics27-1",
                    "mauth"
                  ]
                }
              }
            },
            "additionalProperties": false
          }
        },
        "gitRepo": {
          "type": "string",
          "format": "uri"
        },
        "recommendedVersion": {
          "type": "string"
        },
        "goVersion": {
          "type": "string",
          "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
          "description": "Minimum accepted go version to build the binary."
        },
        "compatibleVersions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cosmosSdkVersion": {
          "type": "string"
        },
        "cosmwasmVersion": {
          "type": "string"
        },
        "cosmwasmEnabled": {
          "type": "boolean"
        },
        "cosmwasmPath": {
          "type": "string",
          "description": "Relative path to the cosmwasm directory. ex. $HOME/.juno/data/wasm",
          "pattern": "^\\$HOME.*$"
        },
        "ibcGoVersion": {
          "type": "string"
        },
        "icsEnabled": {
          "type": "array",
          "description": "List of IBC apps (usually corresponding to a ICS standard) which have been enabled on the network.",
          "items": {
            "type": "string",
            "description": "IBC app or ICS standard.",
            "enum": [
              "ics20-1",
              "ics27-1",
              "mauth"
            ]
          }
        }
      },
      "additionalProperties": false
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "png": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
          },
          "svg": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
          },
          "theme": {
            "type": "object",
            "properties": {
              "circle": {
                "type": "boolean"
              },
              "primaryColorHex": {
                "type": "string",
                "pattern": "^#[0-9a-fA-F]{6}$"
              },
              "darkMode": {
                "type": "boolean"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          },
          "layout": {
            "type": "string",
            "enum": [
              "logo",
              "logomark",
              "logotype"
            ],
            "description": "logomark == icon only; logotype == text only; logo == icon + text."
          },
          "imageSync": {
            "$ref": "#/$defs/pointer"
          },
          "textPosition": {
            "type": "string",
            "enum": [
              "top",
              "bottom",
              "left",
              "right",
              "integrated"
            ],
            "description": "Indicates in which position the text is placed, in case the layout is 'icon' type, it's required only in this case."
          }
        },
        "if": {
          "properties": {
            "layout": {
              "const": "logo"
            }
          },
          "required": [
            "layout"
          ]
        },
        "then": {
          "required": [
            "text_position"
          ]
        },
        "anyOf": [
          {
            "required": [
              "png"
            ]
          },
          {
            "required": [
              "svg"
            ]
          }
        ],
        "additionalProperties": false
      }
    },
    "description": {
      "type": "string",
      "maxLength": 3000
    },
    "peers": {
      "type": "object",
      "properties": {
        "seeds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/peer"
          }
        },
        "persistentPeers": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/peer"
          }
        }
      },
      "additionalProperties": false
    },
    "apis": {
      "type": "object",
      "properties": {
        "rpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "rest": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "wss": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "grpcWeb": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        },
        "evmHttpJsonrpc": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/endpoint"
          }
        }
      },
      "additionalProperties": false
    },
    "explorers": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/explorer"
      }
    },
    "keywords": {
      "type": "array",
      "maxContains": 20,
      "items": {
        "type": "string"
      }
    },
    "chainName": {
      "type": "string",
      "pattern": "[a-z0-9]+"
    },
    "chainId": {
      "type": "string"
    },
    "preForkChainName": {
      "type": "string",
      "pattern": "[a-z0-9]+"
    },
    "prettyName": {
      "type": "string"
    },
    "updateLink": {
      "type": "string",
      "format": "uri"
    },
    "networkType": {
      "enum": [
        "mainnet",
        "testnet",
        "devnet"
      ]
    },
    "bech32Prefix": {
      "type": "string",
      "description": "The default prefix for the human-readable part of addresses that identifies the coin type. Must be registered with SLIP-0173. E.g., 'cosmos'"
    },
    "bech32Config": {
      "type": "object",
      "description": "Used to override the bech32_prefix for specific uses.",
      "properties": {
        "bech32PrefixAccAddr": {
          "type": "string",
          "description": "e.g., 'cosmos'"
        },
        "bech32PrefixAccPub": {
          "type": "string",
          "description": "e.g., 'cosmospub'"
        },
        "bech32PrefixValAddr": {
          "type": "string",
          "description": "e.g., 'cosmosvaloper'"
        },
        "bech32PrefixValPub": {
          "type": "string",
          "description": "e.g., 'cosmosvaloperpub'"
        },
        "bech32PrefixConsAddr": {
          "type": "string",
          "description": "e.g., 'cosmosvalcons'"
        },
        "bech32PrefixConsPub": {
          "type": "string",
          "description": "e.g., 'cosmosvalconspub'"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "daemonName": {
      "type": "string"
    },
    "nodeHome": {
      "type": "string"
    },
    "keyAlgos": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "secp256k1",
          "ethsecp256k1",
          "ed25519",
          "sr25519",
          "bn254"
        ],
        "uniqueItems": true
      }
    },
    "alternativeSlip44s": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "logoURIs": {
      "type": "object",
      "properties": {
        "png": {
          "type": "string",
          "format": "uri-reference",
          "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.png$"
        },
        "svg": {
          "type": "string",
          "format": "uri-reference",
          "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/chain-registry/master/(|testnets/|_non-cosmos/)[a-z0-9]+/images/.+\\.svg$"
        }
      },
      "additionalProperties": false
    },
    "extraCodecs": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ethermint",
          "injective"
        ],
        "uniqueItems": true
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "peer": {
      "type": "object",
      "required": [
        "id",
        "address"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "endpoint": {
      "type": "object",
      "required": [
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "archive": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": false
    },
    "explorer": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "txPage": {
          "type": "string"
        },
        "accountPage": {
          "type": "string"
        },
        "validatorPage": {
          "type": "string"
        },
        "proposalPage": {
          "type": "string"
        },
        "blockPage": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "pointer": {
      "type": "object",
      "description": "The (primary) key used to identify an object within the Chain Registry.",
      "required": [
        "chainName"
      ],
      "properties": {
        "chainName": {
          "type": "string",
          "description": "The chain name or platform from which the object resides. E.g., 'cosmoshub', 'ethereum', 'forex', or 'nasdaq'"
        },
        "baseDenom": {
          "type": "string",
          "description": "The base denom of the asset from which the object originates. E.g., when describing ATOM from Cosmos Hub, specify 'uatom', NOT 'atom' nor 'ATOM'; base units are unique per platform."
        }
      },
      "additionalProperties": false
    },
    "feeToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        },
        "fixedMinGasPrice": {
          "type": "number"
        },
        "lowGasPrice": {
          "type": "number"
        },
        "averageGasPrice": {
          "type": "number"
        },
        "highGasPrice": {
          "type": "number"
        },
        "gasCosts": {
          "type": "object",
          "properties": {
            "cosmosSend": {
              "type": "number"
            },
            "ibcTransfer": {
              "type": "number"
            }
          },
          "additionalProperties": false,
          "minProperties": 1
        }
      },
      "additionalProperties": false
    },
    "stakingToken": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}

=== chain-registry/chain-registry/registries/full/testnets/sunrisetestnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "chainName": "sunrisetestnet",
  "status": "live",
  "networkType": "testnet",
  "prettyName": "Sunrise Testnet",
  "chainId": "sunrise-test",
  "bech32Prefix": "sunrise",
  "daemonName": "sunrised",
  "nodeHome": "$HOME/.sunrise",
  "keyAlgos": [
    "secp256k1"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "urise",
        "fixedMinGasPrice": 0,
        "lowGasPrice": 0.0025,
        "averageGasPrice": 0.025,
        "highGasPrice": 0.04
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uvrise"
      }
    ]
  },
  "codebase": {
    "gitRepo": "https://github.com/sunriselayer/sunrise",
    "recommendedVersion": "v0.1.1",
    "compatibleVersions": [
      "v0.1.1"
    ],
    "binaries": {
      "linux/amd64": "https://github.com/sunriselayer/sunrise/releases/download/v0.1.1/sunrised"
    },
    "cosmosSdkVersion": "0.50.2",
    "consensus": {
      "type": "cometbft",
      "version": "sunriselayer/sunrise-core v0.0.5-cmt-v0.38.2"
    },
    "ibcGoVersion": "8.0.0",
    "versions": [
      {
        "name": "v0.0.7",
        "recommendedVersion": "v0.0.7",
        "compatibleVersions": [
          "v0.0.7"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/sunriselayer/sunrise/releases/download/v0.0.7/sunrised"
        },
        "cosmosSdkVersion": "0.50.2",
        "consensus": {
          "type": "cometbft",
          "version": "sunriselayer/sunrise-core v0.0.5-cmt-v0.38.2"
        },
        "ibcGoVersion": "8.0.0",
        "icsEnabled": [
          "ics20-1"
        ]
      },
      {
        "name": "v0.0.8",
        "recommendedVersion": "v0.0.8",
        "compatibleVersions": [
          "v0.0.8"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/sunriselayer/sunrise/releases/download/v0.0.8/sunrised"
        },
        "cosmosSdkVersion": "0.50.2",
        "consensus": {
          "type": "cometbft",
          "version": "sunriselayer/sunrise-core v0.0.5-cmt-v0.38.2"
        },
        "ibcGoVersion": "8.0.0",
        "icsEnabled": [
          "ics20-1"
        ]
      },
      {
        "name": "v0.1.1",
        "recommendedVersion": "v0.1.1",
        "compatibleVersions": [
          "v0.1.1"
        ],
        "binaries": {
          "linux/amd64": "https://github.com/sunriselayer/sunrise/releases/download/v0.1.1/sunrised"
        },
        "cosmosSdkVersion": "0.50.2",
        "consensus": {
          "type": "cometbft",
          "version": "sunriselayer/sunrise-core v0.0.5-cmt-v0.38.2"
        },
        "ibcGoVersion": "8.0.0",
        "icsEnabled": [
          "ics20-1"
        ]
      }
    ]
  },
  "logoURIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/sunrise/images/sunrise.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/sunrise/images/sunrise.svg"
  },
  "peers": {
    "seeds": [

    ],
    "persistentPeers": [

    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://sunrise-test-1.cauchye.net/",
        "provider": "CauchyE"
      }
    ],
    "rest": [
      {
        "address": "https://sunrise-test-1.cauchye.net:1318",
        "provider": "CauchyE"
      }
    ],
    "grpc": [
      {
        "address": "https://sunrise-test-1.cauchye.net:9092",
        "provider": "CauchyE"
      }
    ]
  },
  "explorers": [

  ],
  "images": [
    {
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/sunrise/images/sunrise.svg",
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/sunrise/images/sunrise.png"
    }
  ]
}

=== chain-registry/chain-registry/registries/full/impacthub/chain.json
{
  "$schema": "../chain.schema.json",
  "chainName": "impacthub",
  "status": "live",
  "networkType": "mainnet",
  "website": "https://www.ixo.world/",
  "prettyName": "Impacts Hub",
  "chainId": "ixo-5",
  "bech32Prefix": "ixo",
  "daemonName": "ixod",
  "nodeHome": "$HOME/.ixod",
  "keyAlgos": [
    "secp256k1",
    "ed25519"
  ],
  "slip44": 118,
  "fees": {
    "feeTokens": [
      {
        "denom": "uixo",
        "fixedMinGasPrice": 0.025,
        "lowGasPrice": 0.025,
        "averageGasPrice": 0.025,
        "highGasPrice": 0.04
      }
    ]
  },
  "staking": {
    "stakingTokens": [
      {
        "denom": "uixo"
      }
    ]
  },
  "codebase": {
    "gitRepo": "https://github.com/ixofoundation/ixo-blockchain",
    "recommendedVersion": "v3.0.0",
    "compatibleVersions": [
      "v3.0.0"
    ],
    "cosmosSdkVersion": "v0.45.16",
    "ibcGoVersion": "v4.4.1",
    "consensus": {
      "type": "cometbft",
      "version": "v0.34.27"
    },
    "genesis": {
      "genesisUrl": "https://github.com/ixofoundation/genesis/raw/bc042e1223d551b22d55c155de06e662ca24d2f2/ixo-5/genesis.json.tar.gz"
    },
    "versions": [
      {
        "name": "v0.20.0",
        "proposal": 403,
        "height": 1254500,
        "recommendedVersion": "v0.20.1",
        "compatibleVersions": [
          "v0.20.0",
          "v0.20.1"
        ],
        "cosmosSdkVersion": "v0.45.12",
        "ibcGoVersion": "v4.3.0",
        "consensus": {
          "type": "tendermint",
          "version": "v0.34.24"
        },
        "nextVersionName": "v2"
      },
      {
        "name": "v2",
        "proposal": 439,
        "height": 2383000,
        "recommendedVersion": "v2.0.0",
        "compatibleVersions": [
          "v2.0.0"
        ],
        "cosmosSdkVersion": "v0.45.16",
        "ibcGoVersion": "v4.4.1",
        "consensus": {
          "type": "cometbft",
          "version": "v0.34.27"
        },
        "nextVersionName": "v3"
      },
      {
        "name": "v3",
        "proposal": 447,
        "height": 6556300,
        "recommendedVersion": "v3.0.0",
        "compatibleVersions": [
          "v3.0.0"
        ],
        "cosmosSdkVersion": "v0.45.16",
        "ibcGoVersion": "v4.4.1",
        "consensus": {
          "type": "cometbft",
          "version": "v0.34.27"
        },
        "nextVersionName": ""
      }
    ]
  },
  "logoURIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/impacthub/images/ixo.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/impacthub/images/ixo.svg"
  },
  "peers": {
    "seeds": [
      {
        "id": "36e4738c7efcf353d3048e5e6073406d045bae9d",
        "address": "80.64.208.43:26656",
        "provider": "simplyvc"
      },
      {
        "id": "20e1000e88125698264454a884812746c2eb4807",
        "address": "seeds.lavenderfive.com:16656",
        "provider": "Lavender.Five Nodes üêù"
      },
      {
        "id": "8542cd7e6bf9d260fef543bc49e59be5a3fa9074",
        "address": "seed.publicnode.com:26656",
        "provider": "Allnodes ‚ö°Ô∏è Nodes & Staking"
      },
      {
        "id": "9194ed56c5b93a0a7e3bdbcad8f62467f7137f56",
        "address": "seed-ixo.ibs.team:16662",
        "provider": "Inter Blockchain Services"
      }
    ],
    "persistentPeers": [
      {
        "id": "36e4738c7efcf353d3048e5e6073406d045bae9d",
        "address": "80.64.208.43:26656",
        "provider": "simplyvc"
      },
      {
        "id": "d4448c5b10b43d444034533ede7d2e66cbf9e519",
        "address": "ixo.peer.stavr.tech:1016",
        "provider": "üî•STAVRüî•"
      }
    ]
  },
  "apis": {
    "rpc": [
      {
        "address": "https://proxies.sifchain.finance/api/impacthub-3/rpc",
        "provider": "sifchain"
      },
      {
        "address": "https://impacthub.ixo.world/rpc/",
        "provider": "ixoworld"
      },
      {
        "address": "https://ixo.rpc.m.stavr.tech:443",
        "provider": "üî•STAVRüî•"
      },
      {
        "address": "https://rpc-ixo-ia.cosmosia.notional.ventures/",
        "provider": "Notional"
      },
      {
        "address": "https://impacthub-rpc.lavenderfive.com/",
        "provider": "Lavender.Five Nodes üêù"
      },
      {
        "address": "https://ixo-rpc.ibs.team",
        "provider": "Inter Blockchain Services"
      }
    ],
    "rest": [
      {
        "address": "https://proxies.sifchain.finance/api/impacthub-3/rest",
        "provider": "sifchain"
      },
      {
        "address": "https://impacthub.ixo.world/rest/",
        "provider": "ixoworld"
      },
      {
        "address": "https://ixo.api.m.stavr.tech",
        "provider": "üî•STAVRüî•"
      },
      {
        "address": "https://api-ixo-ia.cosmosia.notional.ventures/",
        "provider": "Notional"
      },
      {
        "address": "https://impacthub-api.lavenderfive.com/",
        "provider": "Lavender.Five Nodes üêù"
      },
      {
        "address": "https://ixo-api.ibs.team",
        "provider": "Inter Blockchain Services"
      }
    ],
    "grpc": [
      {
        "address": "grpc-ixo-ia.cosmosia.notional.ventures:443",
        "provider": "Notional"
      },
      {
        "address": "ixo.grpc.m.stavr.tech:2010",
        "provider": "üî•STAVRüî•"
      },
      {
        "address": "impacthub-grpc.lavenderfive.com:443",
        "provider": "Lavender.Five Nodes üêù"
      }
    ]
  },
  "explorers": [
    {
      "kind": "ezstaking",
      "url": "https://ezstaking.app/ixo",
      "txPage": "https://ezstaking.app/ixo/txs/${txHash}",
      "accountPage": "https://ezstaking.app/ixo/account/${accountAddress}"
    },
    {
      "kind": "üî•STAVRüî•",
      "url": "https://explorer.stavr.tech/IXO-Mainnet",
      "txPage": "https://explorer.stavr.tech/IXO-Mainnet/txs/${txHash}",
      "accountPage": "https://explorer.stavr.tech/IXO-Mainnet/account/${accountAddress}"
    },
    {
      "kind": "bigdipper",
      "url": "https://blockscan.ixo.world",
      "txPage": "https://blockscan.ixo.world/transactions/${txHash}"
    },
    {
      "kind": "ping.pub",
      "url": "https://ping.pub/ixo",
      "txPage": "https://ping.pub/ixo/tx/${txHash}"
    },
    {
      "kind": "atomscan",
      "url": "https://atomscan.com/ixo",
      "txPage": "https://atomscan.com/ixo/transactions/${txHash}",
      "accountPage": "https://atomscan.com/ixo/accounts/${accountAddress}"
    },
    {
      "kind": "Mintscan",
      "url": "https://www.mintscan.io/ixo",
      "txPage": "https://www.mintscan.io/ixo/transactions/${txHash}",
      "accountPage": "https://www.mintscan.io/ixo/accounts/${accountAddress}"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/impacthub/images/ixo.png",
      "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/impacthub/images/ixo.svg"
    }
  ]
}
